Override time-zone option when initializing database
Initializing database with a config that specifies `default-time-zone` ends up with an error:

> Fatal error: Illegal or unknown default time zone 'Europe/Tallinn'

This adds a workaround to the problem to force the system timezone, so the database can be initialized, and timezones be imported after database init.